[package]
name = "wi"
version = "0.1.0"
edition = "2021"
[lib]
crate-type=["rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
futures-intrusive = "0.5.0"
wgpu = "0.14.2"
pollster = "0.2.5"
image = "0.24.5"